# Используем Node.js image для сборки React
FROM node:16

# Рабочая директория
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем весь проект
COPY . .

# Запускаем сборку React
RUN npm run build

# Устанавливаем сервер для обслуживания статических файлов
# Используем 'serve', который будет обслуживать ваши статику
RUN npm install -g serve

# Открываем порт, на котором будет работать приложение
EXPOSE 3000

# Запускаем приложение с помощью serve на порту 3000
CMD ["serve", "-s", "build", "-l", "3000"]
