version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: ./server
    environment:
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: your_db_name
      DB_HOST: db
      DB_PORT: 5432
    ports:
    - "5000:5000"
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  postgres-data: {}